"""LoggingPort — Infrastructure Port for M4.10."""
from __future__ import annotations
from abc import ABC, abstractmethod
from typing import Any

class LoggingPort(ABC):
    @abstractmethod
    def debug(self, message: str, **kwargs: Any) -> None: ...
    @abstractmethod
    def info(self, message: str, **kwargs: Any) -> None: ...
    @abstractmethod
    def warning(self, message: str, **kwargs: Any) -> None: ...
    @abstractmethod
    def error(self, message: str, **kwargs: Any) -> None: ...
    @abstractmethod
    def health(self) -> bool: ...
